### ISSUE TITLE
Pull grades directly from ICS 33 website

### ISSUE THREAD

**Issue by ChaseC99** [ChaseC99/ICS33-Grade-Viewer#1]
Currently, the file containing the grades has to be manually uploaded to the GitHub repo. Ideally, the ICS 33 Grade Viewer would be able to download the grades directly from the [ICS 33 website](https://www.ics.uci.edu/~pattis/ICS-33/). The exact link for the grades download is: https://www.ics.uci.edu/~pattis/ICS-33/ics33win18grades.zip

I haven't been able to do it so far because of issues with cross-origin resource sharing.

**Comment by ChaseC99** [comment]
Potential work around? https://stackoverflow.com/questions/22363268/cross-origin-request-blocked

**Comment by ChaseC99** [comment]
Actually, maybe not, looks like that only works for verified apps, not just any webpage

**Comment by ChaseC99** [comment]
So far there are only 2 possible ways to get around this problem:

1. The code for the ICS 33 Grade Viewer is hosted on Pattis's website, so we wouldn't have to deal with cross origin issues
2. Pattis implements CORS on his website, allowing us to access the information from ours. "https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS"

Either way, we would have to ask Pattis to modify his website, and I'm not sure if he would be ok with that.

**Comment by ChaseC99** [comment]
Another possible solution? https://stackoverflow.com/questions/578095/how-to-get-data-with-javascript-from-another-server

**Comment by ChaseC99** [comment]
Oh snap this might be it (similar to last answer) https://stackoverflow.com/questions/23676748/download-zip-file-with-jquery-from-ajax-post-request

**Comment by ChaseC99** [comment]
Nevermind, it didn't work :(

**Comment by zhaofengli** [comment]
You can host any static site on openlab. The default umask on openlab is pretty pesky (0077), so you need to do `umask 0022` first, or change the permissions manually afterwards (grant o+rx for directories, o+r for files) to avoid 403s.

When that's done, simply create a directory named `public_html`, put your stuff in it, and they will be accessible at https://www.ics.uci.edu/~yourNetID.

**Comment by ChaseC99** [comment]
Oh my gosh, thank you! I didn't realize that we could do that. That should work because then the two sites would be on the same domain; I'll try it out after midterms. Thanks for the help @zhaofengli !!

**Comment by ChaseC99** [comment]
@zhaofengli THANK YOU SO MUCH FOR YOUR HELP!!! Since I got it onto the ics domain, everything works perfectly! Thanks again for the advice, I really appreciate it!
